[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Felipe Baltor", email = "fbaltor@gmail.com"},
]
dependencies = [
    "pandas>=1.5.3",
]
requires-python = ">=3.9"
license = {text = "MIT"}
